### ISSUE TITLE
Rake db migration Loaderror

### ISSUE THREAD

**Issue by ghost** [m0nad/HellRaiser#3]
when i run bundle exec rake db:migrate, i get this following error: 

bundler: failed to load command: rake (/usr/local/bin/rake)
LoadError: cannot load such file -- /usr/share/rubygems-integration/all/specifications/bin/rake
  /usr/local/bin/rake:23:in `load'
  /usr/local/bin/rake:23:in`<top (required)>'

I read somehwere on stackoverflow that it may be a ruby problem so i reinstalled it. now i am greeted with this error: 

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
current directory: /tmp/bundler20160902-12678-1bhz5szdebug_inspector-0.0.2/gems/debug_inspector-0.0.2/ext/debug_inspector
```

/usr/bin/ruby2.3 -r ./siteconf20160902-12678-5es4b5.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20160902-12678-1bhz5szdebug_inspector-0.0.2/gems/debug_inspector-0.0.2 for inspection.
Results logged to /tmp/bundler20160902-12678-1bhz5szdebug_inspector-0.0.2/extensions/x86_64-linux/2.3.0/debug_inspector-0.0.2/gem_make.out

I tired to install debug_inspector but it gave me same error:

gem install debug_inspector -v '0.0.2'
Building native extensions.  This could take a while...
ERROR:  Error installing debug_inspector:
    ERROR: Failed to build gem native extension.

```
current directory: /var/lib/gems/2.3.0/gems/debug_inspector-0.0.2/ext/debug_inspector
```

/usr/bin/ruby2.3 -r ./siteconf20160902-13356-18m694k.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

Is there something that i may be missing?
Im running ubuntu. also i tired running same commands in root but got the same results.

**Comment by vapor99** [comment]
Same problem here with Kali.  No solutions yet

**Comment by CoolerVoid** [comment]
SO you can  try remove the gem debug of gem.lock file...
https://github.com/m0nad/HellRaiser/blob/master/hellraiser/Gemfile.lock#L41
if another gem return error try remove again other gem with error...

Remove debug stuff sometimes dont affect the code...

I imagine this tool you need RVM with ruby2.0 to run... the author have idea to create iso to runs at VM... sooo i wait for this... https://rvm.io/

cheers
