### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by pretech86** [m0nad/HellRaiser#79]
after i installed every things i get this error when i run foreman s

root@kali:~/tools/vulnrbilities_scanners/HellRaiser# foreman s
05:58:15 web.1         | started with pid 1300
05:58:15 actioncable.1 | started with pid 1302
05:58:15 log.1         | started with pid 1303
05:58:15 worker.1      | started with pid 1306
05:58:15 redis.1       | started with pid 1307
05:58:16 redis.1       | 1307:C 21 May 2020 05:58:16.185 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
05:58:16 redis.1       | 1307:C 21 May 2020 05:58:16.185 # Redis version=6.0.1, bits=64, commit=00000000, modified=0, pid=1307, just started
05:58:16 redis.1       | 1307:C 21 May 2020 05:58:16.185 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
05:58:16 redis.1       | 1307:M 21 May 2020 05:58:16.185 * Increased maximum number of open files to 10032 (it was originally set to 1024).
05:58:16 redis.1       | 1307:M 21 May 2020 05:58:16.297 * Running mode=standalone, port=6379.
05:58:16 redis.1       | 1307:M 21 May 2020 05:58:16.298 # Server initialized
05:58:16 redis.1       | 1307:M 21 May 2020 05:58:16.298 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
05:58:16 redis.1       | 1307:M 21 May 2020 05:58:16.298 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
05:58:16 redis.1       | 1307:M 21 May 2020 05:58:16.298 * Loading RDB produced by version 6.0.1
05:58:16 redis.1       | 1307:M 21 May 2020 05:58:16.298 * RDB age 340 seconds
05:58:16 redis.1       | 1307:M 21 May 2020 05:58:16.298 * RDB memory usage when created 0.77 Mb
05:58:16 redis.1       | 1307:M 21 May 2020 05:58:16.298 * DB loaded from disk: 0.000 seconds
05:58:16 redis.1       | 1307:M 21 May 2020 05:58:16.298 * Ready to accept connections
05:58:16 web.1         | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
05:58:16 worker.1      | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
05:58:16 actioncable.1 | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
05:58:16 worker.1      | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
05:58:16 actioncable.1 | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
05:58:17 web.1         | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
05:58:18 actioncable.1 | Puma starting in single mode...
05:58:18 actioncable.1 | * Version 4.3.3 (ruby 2.7.1-p83), codename: Mysterious Traveller
05:58:18 actioncable.1 | * Min threads: 5, max threads: 5
05:58:18 actioncable.1 | * Environment: development
05:58:18 web.1         | Puma starting in single mode...
05:58:18 web.1         | * Version 4.3.3 (ruby 2.7.1-p83), codename: Mysterious Traveller
05:58:18 web.1         | * Min threads: 5, max threads: 5
05:58:18 web.1         | * Environment: development
05:58:24 web.1         | ! Unable to load application: ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
05:58:24 worker.1      | Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:5:in `<top (required)>'
05:58:24 worker.1      | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:81:in `require'
05:58:24 worker.1      | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
05:58:24 worker.1      | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:76:in `each'
05:58:24 worker.1      | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:76:in `block in require'
05:58:24 worker.1      | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `each'
05:58:24 worker.1      | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `require'
05:58:24 worker.1      | /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler.rb:114:in `require'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/config/application.rb:7:in `<top (required)>'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/config/environment.rb:2:in `<top (required)>'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:252:in `boot_system'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/sidekiq-6.0.7/lib/sidekiq/cli.rb:37:in `run'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/sidekiq-6.0.7/bin/sidekiq:31:in `<top (required)>'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/bin/sidekiq:23:in `load'
05:58:24 worker.1      | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/bin/sidekiq:23:in `<main>'
05:58:24 web.1         | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:5:in `<top (required)>'
05:58:24 web.1         |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:81:in `require'
05:58:24 web.1         |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
05:58:24 web.1         |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:76:in `each'
05:58:24 web.1         |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:76:in `block in require'
05:58:24 web.1         |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `each'
05:58:24 web.1         |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `require'
05:58:24 actioncable.1 | ! Unable to load application: ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
05:58:24 web.1         |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler.rb:114:in `require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/config/application.rb:7:in `<top (required)>'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/config/environment.rb:2:in `require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/config/environment.rb:2:in `<top (required)>'
05:58:24 web.1         |        from config.ru:3:in `require'
05:58:24 web.1         |        from config.ru:3:in `block in <main>'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
05:58:24 actioncable.1 | /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/configuration.rb:321:in `load_rackup'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/configuration.rb:246:in `app'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/runner.rb:155:in `load_and_bind'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/single.rb:98:in `run'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:5:in `<top (required)>'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/launcher.rb:172:in `run'
05:58:24 actioncable.1 |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:81:in `require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/cli.rb:80:in `run'
05:58:24 actioncable.1 |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/bin/puma:10:in `<top (required)>'
05:58:24 actioncable.1 |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:76:in `each'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/bin/puma:23:in `load'
05:58:24 actioncable.1 |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:76:in `block in require'
05:58:24 web.1         |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/bin/puma:23:in `<main>'
05:58:24 actioncable.1 |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `each'
05:58:24 actioncable.1 |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `require'
05:58:24 actioncable.1 |        from /var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler.rb:114:in `require'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/config/application.rb:7:in `<top (required)>'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/config/environment.rb:2:in `require'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/config/environment.rb:2:in `<top (required)>'
05:58:24 actioncable.1 |        from cable/config.ru:1:in `require_relative'
05:58:24 actioncable.1 |        from cable/config.ru:1:in `block in <main>'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/configuration.rb:321:in `load_rackup'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/configuration.rb:246:in `app'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/runner.rb:155:in `load_and_bind'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/single.rb:98:in `run'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/launcher.rb:172:in `run'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/lib/puma/cli.rb:80:in `run'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/gems/puma-4.3.3/bin/puma:10:in `<top (required)>'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/bin/puma:23:in `load'
05:58:24 actioncable.1 |        from /root/tools/vulnrbilities_scanners/HellRaiser/vendor/ruby/2.7.0/bin/puma:23:in `<main>'
05:58:24 web.1         | exited with code 1
05:58:24 system        | sending SIGTERM to all processes
05:58:24 actioncable.1 | exited with code 1
05:58:24 redis.1       | 1307:signal-handler (1590055104) Received SIGTERM scheduling shutdown...
05:58:24 redis.1       | 1307:M 21 May 2020 05:58:24.140 # User requested shutdown...
05:58:24 redis.1       | 1307:M 21 May 2020 05:58:24.140 * Saving the final RDB snapshot before exiting.
05:58:24 redis.1       | 1307:M 21 May 2020 05:58:24.169 * DB saved on disk
05:58:24 redis.1       | 1307:M 21 May 2020 05:58:24.169 # Redis is now ready to exit, bye bye...
05:58:24 log.1         | terminated by SIGTERM
05:58:24 worker.1      | exited with code 1
05:58:24 redis.1       | exited with code 0

**Comment by m0nad** [comment]
Should be fixed now
