### ISSUE TITLE
Error of Run Step (Json ParserError)

### ISSUE THREAD

**Issue by ujkim** [m0nad/HellRaiser#81]
Thank you for distributing a good service.

However, as a result of performing it as it is, an unexpected token error occurs when executing "Run". Can you tell me what it is?

It would be better if Docker is present, but if it's there any version information that it depends on?
I used Rails 6.0.3, Ruby 2.6.6 and Gem 2.6.6 versions.

The error log is below. (nmap result is appeared in HellRaiser logging)
Can you get some hints for the problem?

`20:47:14 worker.1      | Service detection performed. Please report any incorrect results at http://nmap.org/submit/ .
20:47:14 worker.1      | Nmap done: 1 IP address (1 host up) scanned in 38.54 seconds
20:47:14 worker.1      | 2020-06-01T11:47:14.901Z pid=29117 tid=pv9l9 class=HellraiserWorker jid=469e9a7bdf892e68d6900787 elapsed=39.403 INFO: fail
20:47:14 worker.1      | 2020-06-01T11:47:14.902Z pid=29117 tid=pv9l9 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"HellraiserWorker","args":[1],"jid":"469e9a7bdf892e68d6900787","created_at":1591011995.4976509,"enqueued_at":1591011995.4977326},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"class\":\"HellraiserWorker\",\"args\":[1],\"jid\":\"469e9a7bdf892e68d6900787\",\"created_at\":1591011995.4976509,\"enqueued_at\":1591011995.4977326}"}
20:47:14 worker.1      | 2020-06-01T11:47:14.902Z pid=29117 tid=pv9l9 WARN: JSON::ParserError: 767: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
20:47:14 worker.1      | <html><head>
20:47:14 worker.1      | <title>400 Bad Request</title>
20:47:14 worker.1      | </head><body>
20:47:14 worker.1      | <h1>Bad Request</h1>
20:47:14 worker.1      | <p>Your browser sent a request that this server could not understand.<br />
20:47:14 worker.1      | </p>
20:47:14 worker.1      | </body></html>
`

**Comment by m0nad** [comment]
HellRaiser depends on the cve-search(https://github.com/cve-search/cve-search) public API. Unfortunately, this API was removed from public access.
It's needed now to create your own and change the configuration to point to it.

**Comment by ujkim** [comment]
Thank you for response!
Can I solve the public access problem just by changing the setting information?
Or is it necessary to add new features to replace public access?

Have a great day!

**Comment by m0nad** [comment]
You just need to change this config.yml - https://github.com/m0nad/HellRaiser/blob/master/config/config.yml 

Change 'cvesearch_api_domain' field to the domain or IP address of your cve-search instange.

Best regards
